<a href="https://colab.research.google.com/github/SoIllEconomist/ds4b/blob/master/python_ds4b/00_introduction/01_python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Basics

## Expressions
An expression **represents** something
    
- Python **evaluates it** (turns it into a value)
- Similar to a calculator

### Examples
Literal: Evaluates to self

In [0]:
2.3 

An expression with four literals and some operators

In [0]:
(3*7 + 2) * 0.1

## How to tell the Type of a Values

Command:
```python
type(<value>)
```

In [0]:
type(2)

## Variables and Data Types

### Variable Assignment

In [0]:
x = 5

In [7]:
x

5

### Calculations with Variables
| **Operations** | **Example** | **Description**                 |
|----------------|-------------|---------------------------------|
| `+`            | `x+2`       | Sum of two variables            |
| `-`            | `x-2`       | Subtraction of two variables    |
| `*`            | `x*2`       | Multiplication of two variables |
| `**`           | `x**2`      | Exponentiation of a variable    |
| `%`            | `x%2`       | Remainder of a variable         |
| `/`            | `x/2.`      | Division of a variable          |

### Exercise
Try each of the examples in the code cell below:


### Types and Type Conversion

| **Type**           | **Conversion Function** | **Example**       | **Conversion Description** |
|--------------------|-------------------------|-------------------|----------------------------|
| **String**         | `str()`                 | '5','3.45','True' | Variables to strings       |
| **Integer**        | `int()`                 | 5,3,1             | Variables to integers      |
| **Floating point** | `float()`               | 5.0, 3.45, 1.0    | Variables to floats        |
| **Boolean**        | `bool()`                | True, True, True  | Variables to booleans      |

---

#### str (string) for text

**Values:** any sequence of characters

**Operation(s):** + (contenation, or concatenation)
- operator `+` changes from type to type
    
**String literal:** sequence of characters in quotes
- Double quotes: "abc#&$g<" or "Hello World!"
- Single quotes: 'Hello World'

**Concatenation** applies only to strings
- "ab"  + "cd" evaluates to "abcd"
- "ab" + 2 produces an **ERROR**
---
#### Types: int (integers)

**Values:** $\dots , -3, -2, -1, 0, 1, 2, 3, 4, 5, \dots$

**Operations:** + ,- ,* , ** ,/ , // , %


---
#### float (floating point)

**Values:** (approximations of) real numbers
- With a ".": a **float** literal (e.g., 2.0)
- Without a decimal: an **int** literal (e.g., 2)
    
**Operations:** + ,- ,\* ,/ ,\*\*
- *Notice:* operator meaning can change from type to type

---

## Type: bool (boolean)

**Values:** True, False
- Booleans literals `True` and `False` (MUST BE CAPITALIZED)
    
**Operations:** not, and, or
- not b: **True** if *b is false* and **False** if b is true
- b and c: **True** if *both b and c are true*; **False** otherwise
- b or c: **True** if *b is true or c is true*; **False** otherwise

Often come from comparing `int` or `float` values
- Order comparisons: `i<j` `i<=j` `i>=j` `i>j`
- Equality, inequality: `i == j` `i!=j`



## Strings

- Strings are not like integers, floats, and booleans. 
- A string is a **sequence**, which means it is an ordered collection of other values.
  

In [0]:
my_string = 'thisStringIsAwesome'

In [13]:
my_string

'thisStringIsAwesome'

String multiplication causes repeats.

In [15]:
my_string * 2

'thisStringIsAwesomethisStringIsAwesome'

String addition concatenates another string. 

In [16]:
my_string + 'Innit'

'thisStringIsAwesomeInnit'

The word `in` is a boolean operator that takes two strings and returns `True` if the first appears as a substring in the second:

In [17]:
'm' in my_string

True

### String Operations

- A string is a sequence of characters
- You can access the characters one at a time with the bracket operator:

In [11]:
fruit = 'coconut'
letter = fruit[1]
letter

'o'

The expression in brackets is called an index. The index indicates which character in the sequence you want (hence the name).

- For most people, the first letter of 'coconut' is c, not o. 
- But for computer scientists, the index is an offset from the beginning of the string, and the offset of the first letter is zero.

In [12]:
letter = fruit[0]
letter

'c'

### String slices

**Slice:** a segment of a string.
- Selecting a slice is similar to selecting a character
- The operator `[n:m]` returns the part of the string from the $n^{th}$ character to the $m^{th}$ character
    - including the first but excluding the last.

In [19]:
my_string[3]

's'

In [20]:
my_string[4:9]

'Strin'

### String Methods

- Strings provide methods that perform a variety of useful operations. 
- A method is similar to a function—it takes arguments and returns a value—but the syntax is different.

Instead of the function syntax `upper(word)`, it uses the method syntax `word.upper()`.

- This form of dot notation specifies the name of the method, upper, and the name of the string to apply the method to, word. 

- The empty parentheses indicate that this method takes no arguments.

- A method call is called an **invocation**;

| **Method**   | **Example**                  | **Description**         |
|--------------|------------------------------|-------------------------|
| `.upper()`   | `my_string.upper()`          | String to uppercase     |
| `.lower()`   | `my_string.lower()`          | String to lowercase     |
| `.count()`   | `my_string.count('w')`       | Count String elements   |
| `.replace()` | `my_string.replace('e','i')` | Replace String elements |
| `.strip()`   | `my_string.strip()`          | Strip whitespaces       |

### Exercise
Try each of the examples in the code cell below:

## Lists
- **list:** sequence of values
- Values inside of lists are **elements** or **items**
- There are several ways to create a new list;
    - the simplest is to enclose the elements in square brackets `[]`

In [0]:
a = 'is'
b = 'nice'
my_list = ['my','list',a,b]
my_list2 = [[4,5,6,7],[3,4,5,6]]

### Selecting List Elements

- Syntax for accessing the elements of a list is the same as for accessing the characters of a string—the bracket operator.
- The expression inside the brackets specifies the index. 
- Remember that the indices start at 0.

#### Subset


Select item at index 1

In [22]:
my_list[1]

'list'

Select 3rd last item

In [23]:
my_list[-3]

'list'

#### Slice

Select itmens at index 1 and 2

In [24]:
 my_list[1:3]

['list', 'is']

Select items after index 0

In [25]:
my_list[1:]

['list', 'is', 'nice']

Select items before index 3

In [26]:
 my_list[:3]

['my', 'list', 'is']

Copy `my_list`

In [27]:
 my_list[:]

['my', 'list', 'is', 'nice']

#### Subset List of Lists

`my_list[list][itemOfList]`

In [28]:
my_list2[1][0]

3

In [29]:
my_list2[1][:2]

[3, 4]

## List Operations

In [30]:
my_list + my_list

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [31]:
my_list * 2

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [32]:
my_list2 > 4

TypeError: ignored

### List Methods

| **Method**    | **Example**              | **Description**           |
|---------------|--------------------------|---------------------------|
| `.index`      | `my_list.index(a)`       | Get the index of an item  |
| `.count()`    | `my_list.count(a)`       | Count an item             |
| `.append()`   | `my_list.append('!')`    | Append an item at the end |
| `.remove()`   | `my_list.remove('!')`    | Remove an item            |
| `del`         | `del(my_list[0:1])       | Remove an item            |
| `.revserse()` | `my_list.reverse()`      | Reverse the list          |
| `.extend()`   | `my_list.extend('!')`    | Append an item            |
| `.pop()`      | `my_list.pop(-1)`        | Remove an item            |
| `.insert()`   | `my_list.insert(0, '!')` | Insert an item            |
| `.sort()`     | `my_list.sort()`         | Sort the list             |

### Exercise
Try each of the examples in the code cell below:

## Libraries

Most common libraries we will be using in the book:

1. Pandas
1. NumPy
1. matplotlib
1. seaborn
1. sklearn

### Import libraries

In [0]:
import numpy
import numpy as np

### Selective import

In [0]:
from math import pi

## NumPy Arrays

In [0]:
my_list = [1,2,3,4]
my_array = np.array(my_list)
my_2darray = np.array([[1,2,3], [4,5,6]])

### Selecting Numpy Array Elements

#### Subset

In [36]:
my_array[1] # Select item at index 1

2

#### Slice

In [37]:
my_array[0:2] Select items at index 0 and 1

array([1, 2])

#### Subset 2D Numpy arrays

`my_2darray[rows,columns]`

In [38]:
my_2darray[:,0]

array([1, 4])

### NumPy Array Operations

In [39]:
my_array > 3

array([False, False, False,  True])

In [40]:
my_array * 2

array([2, 4, 6, 8])

In [41]:
my_array + np.array([5,6,7,8])

array([ 6,  8, 10, 12])

### NumPy Array Functions

| **Method**    | **Example**                 | **Description**                 |
|---------------|-----------------------------|---------------------------------|
| `.shape`      | `my_array.shape`            | Get the dimensions of the array |
| `np.append()` | `np.append(other_array)`    | Append items to an array        |
| `np.insert()` | `np.insert(my_array, 1, 5)` | Insert items in an array        |
| `np.delete()` | `np.delete(my_array, [1])`  | Delete items in an array        |
| `np.mean()`   | `np.mean(my_array)`         | Mean of the array               |
| `np.median()` | `np.median(my_array)`       | Median of the array             |
| `.corrcoef()` | `my_array.corrcoef()`       | Correlation coefficient         |
| `np.std()`    | `np.std(my_array)`          | Standard deviation              |

### Exercise
Try each of the examples in the code cell below: